"""Add comment reply

Revision ID: 029052b81b77
Revises: 2b87dae02041
Create Date: 2024-10-23 19:12:41.142216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029052b81b77'
down_revision: Union[str, None] = '2b87dae02041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reply_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['reply_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'reply_to')
    # ### end Alembic commands ###
