"""Add created at

Revision ID: 2d193a5466ee
Revises: 029052b81b77
Create Date: 2024-10-23 19:19:55.816319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d193a5466ee'
down_revision: Union[str, None] = '029052b81b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_at')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
