"""Add auto_reply

Revision ID: 48e333ea4897
Revises: 2d193a5466ee
Create Date: 2024-10-23 21:34:25.877386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e333ea4897'
down_revision: Union[str, None] = '2d193a5466ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comments_reply', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('auto_reply_delay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_reply_delay')
    op.drop_column('users', 'comments_reply')
    # ### end Alembic commands ###
